### ISSUE TITLE
Error while running the node server of labellab-server

### ISSUE THREAD

**Issue by msk4862** [scorelab/LabelLab#30]
labellab-client is working fine but I'm getting following **error** while running the node server of **labellab-server** using 'npm start'.

C:\Users\msk\Desktop\open_source\LabelLab\labellab-server\node_modules\passport-oauth2\lib\strategy.js: 100
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^
TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (C:\Users\msk\Desktop\open_source\LabelLab\labellab-server\node_modules\passport-oauth2\lib\strategy.js: 100:34)
    at new Strategy (C:\Users\msk\Desktop\open_source\LabelLab\labellab-server\node_modules\passport-github\lib\strategy.js:62:18)
    at Object.<anonymous> (C:\Users\msk\Desktop\open_source\LabelLab\labellab-server\config\github_passport.js:9:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\msk\Desktop\open_source\LabelLab\labellab-server\routes\auth\routes.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! labellab-server@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the labellab-server@0.0.0 start script.

I think i've to add my credentials but I can't find that file.
Thanks in advance!

**Comment by Tushar19varshney** [comment]
@msk4862 You have to create `.env` file and put your google client or github client id there.
I have already created a `.`env.example` for sample. You just need to change this file name from `.env.example` to `.env` and add your OAuth credentials there.
I will add instructions to `README.md` for this type of problem.

**Comment by msk4862** [comment]
Okay, Thanks.

**Comment by msk4862** [comment]
i've added github credentials in .env file but now its giving error for not giving **google** credentials.


C:\Users\msk\Desktop\open_source\LabelLab\labellab-server\node_modules\passport-oauth2\lib\strategy.js:100
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^
TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (C:\Users\msk\Desktop\open_source\LabelLab\labellab-server\node_modules\passport-oauth2\lib\strategy.js: 100:34)
    at new Strategy (C:\Users\msk\Desktop\open_source\LabelLab\labellab-server\node_modules\passport-**google**-oauth20\lib\strategy.js:52:18)
    at Object.<anonymous> (C:\Users\msk\Desktop\open_source\LabelLab\labellab-server\config\google_passport.js:9:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\msk\Desktop\open_source\LabelLab\labellab-server\app.js:15:24)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! labellab-server@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the labellab-server@0.0.0 start script.

**Comment by Tushar19varshney** [comment]
@msk4862 For starting the server you need to add both credentials.
That's a good point though. I will change the configuration of OAuth.
